// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcpnzwtdwliqvngvjulg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcG56d3Rkd2xpcXZuZ3ZqdWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjI3OTYsImV4cCI6MjA2MDMzODc5Nn0.uN2JwRgmfICw1-CFxudu6LsKP_S7u4_AIJYZe1kdKpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);